name: CI

on:
  push:
    branches:
      - main
      - codex/kickoff-toolsite-starter
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Unit tests
        if: github.ref != 'refs/heads/feat/i18n-clean'
        run: npm test
      - name: Install Playwright Browsers
        if: github.ref != 'refs/heads/feat/i18n-clean'
        run: npx playwright install --with-deps
      - name: E2E tests
        if: github.ref != 'refs/heads/feat/i18n-clean'
        run: npm run e2e
      - name: Lighthouse CI
        if: github.ref != 'refs/heads/feat/i18n-clean'
        run: npm run lh
